version: '3.9'
services:
  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      REACT_APP_ENDPOINT_API: http://localhost:3001
  backend:
    build: ./back-end
    container_name: backend
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    environment:
      PORT: 3001
      MONGO_URI: mongodb://mongodb:27017/BlitzChallenge
  mongodb:
    image: mongo:5.0.6
    container_name: mongodb
    ports:
      - 27017:27017